---
- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false

- name: create node_exporter system user
  user:
    name: node_exporter
    system: true
    shell: "/bin/false"
    group: node_exporter
    createhome: false

- name: "Checking folders"
  stat:
    path: "{{item}}"
  register: folder_stats
  with_items:
  - ["/etc/prometheus","/var/prometheus","/lib/prometheus"]

- name: "Creating multiple folders without disturbing previous permissions"
  file:
    path: "{{item.item}}"
    state: directory
    mode: 0770
    group: prometheus
    owner: prometheus
  when: item.stat.exists == false
  loop:
  - "{{folder_stats.results}}"

- name: Distribution of binaries to the necessary directories
- block:
      name: Copy prometheus, promtool
      copy:
        src: "/tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
        owner: prometheus
        group: prometheus
      with_items:
          - prometheus
          - promtool
      name: Copy console_libraries, consoles, prometheus.yml
      copy:
        src: "/tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
          - console_libraries
          - consoles
          - prometheus.yml
      name: Copy node_exporter binary
      copy:
        src: "/tmp/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/"
        mode: 0755
        owner: node_exporter
        group: node_exporter

- name: Create services
- block:
    - name: Create prometheus.service
      template: 
        src: templates/prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: 0444
      notify: restart prometheus

    - name: Create node_exporter.service
      template: 
        src: templates/node_exporter.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: 0444
      notify: restart node_exporter
