---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install packages to allow apt to use a repository over HTTPS.
  apt:
    name: "{{ https_packages }}"
    state: present

- block:
    - name: Download prometheus {{ prometheus_version }} release
      file:
        path: /tmp/prometheus
        state: directory
        mode: '0755'
      get_url:
        url: {{ prometheus_url }}
        dest: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
        mode: '0644'
      unarchive:
        src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
        dest: /tmp/prometheus/
        remote_src: yes

    - name: Download node_exporter {{ node_exporter_version }} release
      get_url:
        url: {{ node_exporter_url }}
        dest: /tmp/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        mode: '0644'
      unarchive:
        src: /tmp/prometheus/
        dest: /tmp/prometheus/
        remote_src: yes

