---
- name: Ensure a list of packages installed
  apt:
    name: "{{ https_packages }}"
    state: present
    update_cache: true

- name: Add google pub key
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Add repository into sources list
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install google-chrome-stable
  apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true
