---
https_packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg
- lsb-release
- wget
prometheus_version: "2.32.1"
node_exporter_version: "1.3.1"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"