---
- name: install sudo
  apt:
    name: sudo
    state: present
  tags: [sudo]

- name: create sudoers files
  copy:
    dest: '/etc/sudoers.d/90_{{ item }}'
    content: "%{{ item }} ALL=(ALL:ALL) NOPASSWD: ALL\n"
    owner: root
    group: root
    mode: '0400'
  with_items: '{{ sudoers_groups }}'
  tags: [sudo]

- name: delete sudoers files
  file:
    path: '/etc/sudoers.d/90_{{ item }}'
    state: absent
  with_items: '{{ sudoers_groups_absent }}'
  tags: [sudo]

- name: configure sudo
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: '0400'
- import_tasks: config.yml
  tags: [sudo]

