---
- name: Install Ansible.
  apt:
    name: ansible
    state: present

- name: Install Docker Engine.
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Clean up the apt cache
  apt:
    autoclean: true

- name: Automatically remove any unused dependencies
  apt:
    autoremove: true
