---
- name: Uninstall old versions packages.
  apt:
    name: "{{ old_packages }}"
    state: absent

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install packages to allow apt to use a repository over HTTPS.
  apt:
    name: "{{ https_packages }}"
    state: present

- name: Add ansible repository.
  apt_repository:
    repo: 'ppa:ansible/ansible'
    update_cache: true

- name: Add Docker apt key.
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker repos.
  apt_repository:
    filename: docker
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    state: present
    update_cache: true

