---
- name: Update
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Ensure a list of packages installed
  apt:
    name: "{{ req_packages }}"
    state: present

- name: Clean up the apt cache
  apt:
    autoclean: true

- name: Automatically remove any unused dependencies
  apt:
    autoremove: true
