---
- name: Ensure a list of packages installed
  apt:
    name: "{{ https_packages }}"
    state: present
    update_cache: true

- name: Add hashicorp key&repo
  apt_key:
    id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
    url: "https://apt.releases.hashicorp.com/gpg"
  apt_repository:
    filename: hashicorp
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present
    update_cache: true

- name: Install vagrant
  apt:
    name: vagrant
    state: present

- name: Install packer
  apt:
    name: packer
    state: present
